[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
size = 28

[general]
import = ["~/.config/alacritty/themes/kanagawa/kanagawa_wave.toml"]



















