[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized"

[font]
size = 24

[font.normal]
#family = "Hack Nerd Font"
#family = "Monaspace Neon"
family = "FiraCode Nerd Font"
style = "Regular"

[general]
# import = ["~/.config/alacritty/themes/kanagawa/kanagawa_wave.toml"]

[colors.primary]
background = "#000000"



















