[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "Buttonless"
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 24

[font.normal]
#family = "Hack Nerd Font"
#family = "Monaspace Neon"
family = "FiraCode Nerd Font"
style = "Regular"

[general]
# import = ["~/.config/alacritty/themes/kanagawa/kanagawa_wave.toml"]

[colors.primary]
background = "#000000"

[colors.normal]
magenta = "0xb3243e"
cyan 	= "0x7fe5d4"
